services:
    app:
        build:
            context: .
            dockerfile: docker/php/roadrunner.dockerfile
        container_name: laravel_octane_roadrunner
        restart: always
        ports:
            - "9807:9807"
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            OCTANE_SERVER: roadrunner
            APP_ENV: ${APP_ENV}
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    db:
        image: mysql:8.0
        container_name: laravel_octane_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "${DB_PORT}:${DB_PORT}"

volumes:
    db_data:
