<?php

namespace Domains\Transaction\Requests;

use Domains\Transaction\States\Status\TransactionStatus;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class TransactionUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<mixed>
     */
    public function rules()
    {
        return [
            'status' => ['required', Rule::in(TransactionStatus::toValues()),]
        ];
    }

    public function messages()
    {
        $parent_messages = parent::messages(); // TODO: Change the autogenerated stub

        $messages = [
            'status.required' => __('app.validation.required', ['attribute' => __('app.transaction.status')]),
            'status.in'       => __('app.validation.in', ['attribute' => __('app.transaction.status')]),
        ];

        return array_merge($parent_messages, $messages);
    }
}
