<?php

namespace Domains\Category\Requests;

class CategoryStoreRequest extends \Illuminate\Foundation\Http\FormRequest
{
    public function rules(): array
    {
        return [
            'name'                => 'required|array',
            'name.*'              => 'required|string|min:3|max:255',
            'short_description'   => 'nullable|array',
            'short_description.*' => 'nullable|string|min:3|max:255',
            'is_active'           => 'required|boolean',
            'logo'                => 'nullable|string|min:0|max:255',
            'order_num'           => 'required|integer',
            'created_at'          => 'nullable|date',
            'updated_at'          => 'nullable|date',
        ];
    }

    public function authorize(): bool
    {
        return true;
    }

    public function messages()
    {
        $parent_messages = parent::messages(); // TODO: Change the autogenerated stub

        $locales = config('app.locales');
        $messages = [];
        foreach ($locales as $locale) {
            $messages["name.$locale.required"] = __('validation.required', ['attribute' => __('app.label.names') . " ($locale)"]);
            $messages["name.$locale.string"] = __('validation.string', ['attribute' => __('app.label.names') . " ($locale)"]);
            $messages["name.$locale.min"] = __('validation.min.string', ['attribute' => __('app.label.names') . " ($locale)", 'min' => 3]);
            $messages["name.$locale.max"] = __('validation.max.string', ['attribute' => __('app.label.names') . " ($locale)", 'max' => 255]);
        }

        return array_merge($parent_messages, $messages);
    }
}
